spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id : member-service
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/members/**
