spring:
  application:
    name: api-gateway
  profiles:
    active: local
    include:
      - routes
      - security

  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
